services:
  - type: web
    name: voltageauto
    env: python
    rootDir: voltageauto_backend
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn voltageauto.wsgi"
    autoDeploy: true
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "voltageauto.onrender.com"
